### ISSUE TITLE
Can not execute command

### ISSUE THREAD

**Issue by with0out** [ntpeters/vim-better-whitespace#44] opened 2016-04-21 07:10 UTC
Windows 7 64bit, vim 7.4, has python2.
While white space highlight works fine, 
![alt text](http://i.imgur.com/yCIc0yJ.png)
when I execute commands, it complains:

```
E116: Invalid arguments for function <SNR>125_ToggleWhitespace
E116: Invalid arguments for function <SNR>125_StripWhitespace
```

And in mingw64's vim command execution works fine.
I used plug.vim to install this plugin, anything I might do to get it working?
Thanks!

**Comment by ntpeters** [comment] 2016-05-14 03:11
Hm, that's odd. Does it do this for all commands?  And is it still doing it on latest?

**Comment by with0out** [comment] 2016-05-15 08:15
Yes, just updated plugin, and ToggleStripWhitespaceOnSave give _E116_ as well.

**Comment by ntpeters** [comment] 2016-05-16 17:37
I'm not sure what could be causing this. Could you try it with a clean `.vimrc` (no other plugins or settings)?  Do you also have another, non-Windows, machine you might be able to try it on? I only have a Mac available to me at the moment, so I'd just like to rule out anything weird there.

**Comment by with0out** [comment] 2016-05-23 17:40
I tried a .vimrc with only 
```
call plug#begin($VIMFILES."/bundle")
Plug 'ntpeters/vim-better-whitespace'
call plug#end()
```
Still the same E116 error.

Install this plugin using Plug seems fine in Debian, so this error is windows only?

**Comment by yodalee** [comment] 2016-07-14 08:34
I ran into same error recently, and I found this related to problem in vim 7.4 patches.
I just upgrade to vim version 7.4.1910 and the problem is solved.

**Comment by ntpeters** [comment] 2018-02-25 06:35
Closing, as this appears to have been a Vim issue that's since been resolved.

**Closed by ntpeters** 2018-02-25 06:35 UTC
