### ISSUE TITLE
Highlight Color is not working for some reason

### ISSUE THREAD

**Issue by tommy20061222** [ntpeters/vim-better-whitespace#41] opened 2015-12-15 15:32 UTC
If i add 'highlight ExtraWhitespace ctermbg=red' to my vimrc, the plugin is not working at all. but if leave my .vimrc untouched, it works perfectly with red highlighting.  

I thought maybe my other configuration was overriding the changes, so put that line at bottom of my vimrc , still no luck.  Can you help me?

I think it is my problem, but i can not figure it out. thank you!

**Comment by dragonxlwang** [comment] 2016-03-31 19:08
my two cents: you probably put the highlight statement immediately after adding the plugin in your vimrc while at that time you still havn't load your color scheme. In most color schemes, highlight first be cleared (but stay existing) and vim-better-whitespace would not set it because of this. 

Easy fix is to put all your highlight after you load your colorscheme.

**Comment by ntpeters** [comment] 2016-05-14 02:47
I'm unable to reproduce this, and agree with @dragonxlwang. Closing for now, but if you still run into problems let me know.

**Closed by ntpeters** 2016-05-14 02:47 UTC
