### ISSUE TITLE
blacklist not working for help files

### ISSUE THREAD

**Issue by oblitum** [ntpeters/vim-better-whitespace#139] opened 2020-07-13 20:50 UTC
Enabled anytime I call `:h something`, which affects help of some plugins I use, `'help'` on blacklist has no effect.

**Comment by oblitum** [comment] 2020-07-13 21:09
Possibly related to #130.

**Comment by Cimbali** [comment] 2020-07-17 00:15
Possibly a duplicate of #108 ? With a workaround in there until someone gets around to improving filetype detection.

**Comment by Cimbali** [comment] 2020-07-17 00:47
Closing for now, feel free to reopen @oblitum if I missed something and this is somehow different.

**Closed by Cimbali** 2020-07-17 00:47 UTC

**Comment by oblitum** [comment] 2020-07-17 01:53
Ah, indeed, sorry for the noise, I did even commented on that issue and completely forgot about it.
